# Generated by Django 2.1.7 on 2019-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleetname', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(blank=True, max_length=10000, null=True)),
                ('chief_engineer', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RedditPost',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='report',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='report',
            name='chief_engineer',
        ),
        migrations.AddField(
            model_name='report',
            name='vessel_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp_local',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp_sutc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
