# Generated by Django 2.1.7 on 2019-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190330_2053'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fleet',
            table='fleet',
        ),
        migrations.AlterModelTable(
            name='vessel',
            table='vessel',
        ),
    ]
