# Generated by Django 2.1.7 on 2019-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190330_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='eta_local',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='eta_utc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
