# Generated by Django 2.1.7 on 2019-03-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190331_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='vessel_id',
            new_name='vessel',
        ),
    ]
